# Generated by Django 5.2.7 on 2025-10-08 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='triggered_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_level',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
