# Generated by Django 5.2.7 on 2025-10-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_alert_severity_remove_alert_triggered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
