# Generated by Django 5.2.7 on 2025-10-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alter_category_name'),
        ('dispositivos', '0003_alter_alert_alert_level'),
    ]

    operations = [
    ]
